### ISSUE TITLE
How to not display the VectorMenusidebar for anonymous?

### ISSUE THREAD

**Issue by Simonlisw** [Mikumikuer/VectorMenuSidebar#3]
This extension is great. But for anonymous visitors, how do you prevent the sidebar from being displayed?

**Comment by Mikumikuer** [comment]
try with getGroups() in **LocalSettings.php**  [Mediawiki php documentation](https://doc.wikimedia.org/mediawiki-core/master/php/classMediaWiki_1_1User_1_1User.html#aa50d10007aad5676167b948895cbc048)
getGroups() return an array, anonymous visitors return only `['*']` , So comapre `getGroups() ==['*']` and set `$wgVectorMenuSidebar = false`  otherwise with true.
